/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'authoritative-documents': AuthoritativeDocument;
    'test-suites': TestSuite;
    'test-cases': TestCase;
    'test-runs': TestRun;
    'input-files': InputFile;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'authoritative-documents': {
      testSuites: 'test-suites';
    };
    'test-suites': {
      testCases: 'test-cases';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'authoritative-documents': AuthoritativeDocumentsSelect<false> | AuthoritativeDocumentsSelect<true>;
    'test-suites': TestSuitesSelect<false> | TestSuitesSelect<true>;
    'test-cases': TestCasesSelect<false> | TestCasesSelect<true>;
    'test-runs': TestRunsSelect<false> | TestRunsSelect<true>;
    'input-files': InputFilesSelect<false> | InputFilesSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'dev-panel': DevPanel;
  };
  globalsSelect: {
    'dev-panel': DevPanelSelect<false> | DevPanelSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'ingest-authoritative-document': TaskIngestAuthoritativeDocument;
      'evaluate-test-case': TaskEvaluateTestCase;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      'process-test-run': WorkflowProcessTestRun;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authoritative-documents".
 */
export interface AuthoritativeDocument {
  id: number;
  title: string;
  docType: 'nist' | 'pci-dss';
  s3Url?: string | null;
  s3Key?: string | null;
  ingestStatus?: ('pending' | 'success' | 'error') | null;
  tableOfContents?: string | null;
  testSuites?: {
    docs?: (number | TestSuite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-suites".
 */
export interface TestSuite {
  id: number;
  title: string;
  alias: string;
  authoritativeDocument?: (number | null) | AuthoritativeDocument;
  testCases?: {
    docs?: (string | TestCase)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-cases".
 */
export interface TestCase {
  id: string;
  title: string;
  suite?: (number | null) | TestSuite;
  methodology?: string | null;
  metadata: {
    /**
     * The version of the NIST control catalog
     */
    version?: string | null;
    pdfPagesRange: string;
    docPagesRange: string;
  };
  links?:
    | {
        href?: string | null;
        relationType?: string | null;
        id?: string | null;
      }[]
    | null;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-runs".
 */
export interface TestRun {
  id: number;
  title?: string | null;
  status?: ('CREATED' | 'FULFILLED' | 'PENDING' | 'COMPLETED' | 'FAILED') | null;
  input?: (number | InputFile)[] | null;
  result?:
    | {
        suites?: {
          suite?: (number | null) | TestSuite;
          cases?:
            | {
                case?: (string | null) | TestCase;
                summary?: {
                  status?: ('COMPLIANT' | 'PARTIALLY_COMPLIANT' | 'NON_COMPLIANT') | null;
                  confidenceLevel?: string | null;
                  briefing?: string | null;
                };
                gaps?:
                  | {
                      title?: string | null;
                      description?: string | null;
                      severity?: ('CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW') | null;
                      documentEvidence?:
                        | {
                            citation?: string | null;
                            location?: string | null;
                            context?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      controlEvidence?:
                        | {
                            citation?: string | null;
                            location?: string | null;
                            context?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      impact?: {
                        security?: string | null;
                        compliance?: string | null;
                        operational?: string | null;
                      };
                      recommendation?: {
                        description?: string | null;
                        priority?: ('HIGH' | 'MEDIUM' | 'LOW') | null;
                        steps?:
                          | {
                              step?: string | null;
                              id?: string | null;
                            }[]
                          | null;
                        expectedOutcome?: string | null;
                      };
                      id?: string | null;
                    }[]
                  | null;
                overallRecommendations?: {
                  priority?: ('HIGH' | 'MEDIUM' | 'LOW') | null;
                  dependencies?:
                    | {
                        dependency?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "input-files".
 */
export interface InputFile {
  id: number;
  title: string;
  hash?: string | null;
  s3Url?: string | null;
  parsedText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'ingest-authoritative-document' | 'evaluate-test-case';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'ingest-authoritative-document' | 'evaluate-test-case') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'process-test-run' | null;
  taskSlug?: ('inline' | 'ingest-authoritative-document' | 'evaluate-test-case') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authoritative-documents';
        value: number | AuthoritativeDocument;
      } | null)
    | ({
        relationTo: 'test-suites';
        value: number | TestSuite;
      } | null)
    | ({
        relationTo: 'test-cases';
        value: string | TestCase;
      } | null)
    | ({
        relationTo: 'test-runs';
        value: number | TestRun;
      } | null)
    | ({
        relationTo: 'input-files';
        value: number | InputFile;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authoritative-documents_select".
 */
export interface AuthoritativeDocumentsSelect<T extends boolean = true> {
  title?: T;
  docType?: T;
  s3Url?: T;
  s3Key?: T;
  ingestStatus?: T;
  tableOfContents?: T;
  testSuites?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-suites_select".
 */
export interface TestSuitesSelect<T extends boolean = true> {
  title?: T;
  alias?: T;
  authoritativeDocument?: T;
  testCases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-cases_select".
 */
export interface TestCasesSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  suite?: T;
  methodology?: T;
  metadata?:
    | T
    | {
        version?: T;
        pdfPagesRange?: T;
        docPagesRange?: T;
      };
  links?:
    | T
    | {
        href?: T;
        relationType?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-runs_select".
 */
export interface TestRunsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  input?: T;
  result?:
    | T
    | {
        suites?:
          | T
          | {
              suite?: T;
              cases?:
                | T
                | {
                    case?: T;
                    summary?:
                      | T
                      | {
                          status?: T;
                          confidenceLevel?: T;
                          briefing?: T;
                        };
                    gaps?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          severity?: T;
                          documentEvidence?:
                            | T
                            | {
                                citation?: T;
                                location?: T;
                                context?: T;
                                id?: T;
                              };
                          controlEvidence?:
                            | T
                            | {
                                citation?: T;
                                location?: T;
                                context?: T;
                                id?: T;
                              };
                          impact?:
                            | T
                            | {
                                security?: T;
                                compliance?: T;
                                operational?: T;
                              };
                          recommendation?:
                            | T
                            | {
                                description?: T;
                                priority?: T;
                                steps?:
                                  | T
                                  | {
                                      step?: T;
                                      id?: T;
                                    };
                                expectedOutcome?: T;
                              };
                          id?: T;
                        };
                    overallRecommendations?:
                      | T
                      | {
                          priority?: T;
                          dependencies?:
                            | T
                            | {
                                dependency?: T;
                                id?: T;
                              };
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "input-files_select".
 */
export interface InputFilesSelect<T extends boolean = true> {
  title?: T;
  hash?: T;
  s3Url?: T;
  parsedText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev-panel".
 */
export interface DevPanel {
  id: number;
  /**
   * If enabled, the tests will be limited to 3 random cases for each suite
   */
  limitTests?: boolean | null;
  /**
   * Number of test cases to process in parallel per workflow batch. Default: 5.
   */
  workflowBatchSize?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev-panel_select".
 */
export interface DevPanelSelect<T extends boolean = true> {
  limitTests?: T;
  workflowBatchSize?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIngest-authoritative-document".
 */
export interface TaskIngestAuthoritativeDocument {
  input: {
    docId: string;
    pagesRange: string;
  };
  output: {
    success: boolean;
    message?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEvaluate-test-case".
 */
export interface TaskEvaluateTestCase {
  input: {
    userDocument: string;
    controlText: string;
    methodology: string;
    traceId: string;
    testCaseId: string;
  };
  output: {
    case?: (string | null) | TestCase;
    summary?: {
      status?: ('COMPLIANT' | 'PARTIALLY_COMPLIANT' | 'NON_COMPLIANT') | null;
      confidenceLevel?: string | null;
      briefing?: string | null;
    };
    gaps?:
      | {
          title?: string | null;
          description?: string | null;
          severity?: ('CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW') | null;
          documentEvidence?:
            | {
                citation?: string | null;
                location?: string | null;
                context?: string | null;
                id?: string | null;
              }[]
            | null;
          controlEvidence?:
            | {
                citation?: string | null;
                location?: string | null;
                context?: string | null;
                id?: string | null;
              }[]
            | null;
          impact?: {
            security?: string | null;
            compliance?: string | null;
            operational?: string | null;
          };
          recommendation?: {
            description?: string | null;
            priority?: ('HIGH' | 'MEDIUM' | 'LOW') | null;
            steps?:
              | {
                  step?: string | null;
                  id?: string | null;
                }[]
              | null;
            expectedOutcome?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    overallRecommendations?: {
      priority?: ('HIGH' | 'MEDIUM' | 'LOW') | null;
      dependencies?:
        | {
            dependency?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    id?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowProcess-test-run".
 */
export interface WorkflowProcessTestRun {
  input: {
    traceId: string;
    currentTestRun: number | TestRun;
    choosedAuthoritativeDocument: number | AuthoritativeDocument;
    choosedTestSuites: (number | TestSuite)[];
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}